### ISSUE TITLE
Increase font in comment boxes

### ISSUE THREAD

**Issue by ejrau** [Willa-Cather-Archive/annotonia#18]
Could we increase the font in Annotonia in the comment boxes? It's difficult for people to accurately proofread when the font is small and not able to be magnified.

**Comment by techgique** [comment]
Yes, this is on my list of things to do 👍

**Comment by techgique** [comment]
Added here: https://github.com/Willa-Cather-Archive/annotonia/commit/aa3573ad2e1b22d4a209f4ecad0b612ab2b17397
