### ISSUE TITLE
auto-size images in annotations 

### ISSUE THREAD

**Issue by ajewell2** [Willa-Cather-Archive/annotonia#19]
Right now when we connect to an image in a letter annotation, the interface shows us the image at full size, making it hard to edit. For example, see the first few annotations in https://cather.unl.edu/annotonia/tei/tei-boilerplate/cat.let2340.html

Please make the default image resize to a smaller, more manageable size. Something like 300px wide would probably work, as long as it is big enough to see the image and small enough to edit around it.

And here's a screenshot:
![image](https://user-images.githubusercontent.com/8901329/41313711-4635a81a-6e50-11e8-9130-257e4ca41716.png)

**Comment by techgique** [comment]
Added here: https://github.com/Willa-Cather-Archive/annotonia/commit/aa3573ad2e1b22d4a209f4ecad0b612ab2b17397
